### ISSUE TITLE
where is your nuget package ?

### ISSUE THREAD

**Issue by pubpy2015** [zgabi/Yolo.Net#1]
Hi,

![ảnh](https://user-images.githubusercontent.com/59004953/111427499-c5afb380-8728-11eb-8bfd-a3519adb14a7.png)

**Comment by zgabi** [comment]
Check the include prerelease checkbox.

**Comment by pubpy2015** [comment]
Thanks,

Is it work with CUDA 11 ?

**Comment by zgabi** [comment]
If you can build you own native yolo dlls, then yes. Otherwise by default it requires cuda 10.2.

**Comment by pubpy2015** [comment]
Thanks,

Where is source i can build yolo_cpp_dll_gpu.dll ?

**Comment by zgabi** [comment]
https://github.com/AlexeyAB/darknet

**Comment by pubpy2015** [comment]
Can i create multi YoloWrapper for detect multi images at same time ?
private YoloWrapper _yoloWrapper;

**Comment by zgabi** [comment]
Sorry, I don't know this. This library is a fork from https://github.com/AlturosDestinations/Alturos.Yolo

Basically it is just calling the native Yolo's detect_image and detect_mat function. So if they are threadsafe, then you can call Yolo.NET's Detect method on the same wrapper object from multiple threads.

**Comment by zgabi** [comment]
I just investigated a little bit, and found, that CUDA probably allows only 1 execution in the same time, so although it is (probably) possible to call it on multiple threads, but it will wait on the real GPU calculation. So it makes useless to call it parallel.
So multi threading will fasten the detection only when you are using the CPU for the object detection. But that is very slow, so single thread GPU is much faster than parallel CPU.

I don't know what is the situation when you have multiple GPUs. In this case probably you could use them parallel, but as far as I see, the native yolo does not support it, so you have to implement that support in the native library. Is this your case?

**Comment by pubpy2015** [comment]
seem some others has this problem:
[https://github.com/AlturosDestinations/Alturos.Yolo/issues/144](url)
[https://github.com/AlturosDestinations/Alturos.Yolo/issues/127](url)

and it's only work when PC has multiple GPU:
[https://github.com/AlturosDestinations/Alturos.Yolo/issues/97](url)

![image](https://user-images.githubusercontent.com/59004953/111472914-0a554200-875d-11eb-8a57-1892b006bc08.png)
