### ISSUE TITLE
Cuda 11 and RTX3000

### ISSUE THREAD

**Issue by AlgirdasKartavicius** [zgabi/Yolo.Net#4]
Is CUDA 11.2 and RTX3000 series supported?

**Comment by zgabi** [comment]
No, CUDA 11.2 is not supported. It neds to build the native yolo library for that.
However it shuold work with RTX3000 with older CUDA.

**Comment by AlgirdasKartavicius** [comment]
Is building yolo library and replacing dll enough?

**Comment by zgabi** [comment]
Probably yes. But i'm not sure.
Anyway if you can build the yolo native library, let me know and i'll check the  .Net part

**Comment by avresial** [comment]
HI, Did it work?

**Comment by avresial** [comment]
Just before texting here i opened new issue on original Alturos.YoloWrapper: [Link to issue.](https://github.com/AlturosDestinations/Alturos.Yolo/issues/186) Might be relevant to the case here.

**Comment by AlgirdasKartavicius** [comment]
> HI, Did it work?

I built yolo native library with CUDA 11.1 and OPENCV support.

**Comment by avresial** [comment]
> > HI, Did it work?
> 
> I built yolo native library with CUDA 11.1 and OPENCV support.

Could you give me any hint how to do that?
1. Is it just building darknet framework, therefore building `darknet.dll` and coping it to projects folder as `yolo_cpp_dll_gpu.dll`?
2. Or maybe it is diferent dll, not the `darknet.dll` and i have to copy different one?
3. Or maybe somethink else?

I did follow [This](https://medium.com/analytics-vidhya/darknet-installation-on-windows-10-fa7af9c5fd23) and [This](https://www.youtube.com/watch?v=WK_2bpWj35A) tutorials. And when it comes to my first question, I already tried that and `yolo_cpp_dll_gpu.dll` is being found but can not be loaded. Maybe you have some online tutorial that could guide me.

Thx for helping

**Comment by avresial** [comment]
Ok
I found out that even when I put right `yolo_cpp_dll_gpu.dll` version to projects folder, when building, that dll is being changed to old one. But when I start the program and hit brake, then put right dll to the place, resume program, all dlls are found correctly.
I can see that in `DefaultYoloSystemValidator.cs`. I changed `yolo_cpp_dll_gpu.dll` to `yolo_cpp_dll_gpu8.dll` not to be overwritten and it works.

``` c#
    const string yoloDllFileName = "yolo_cpp_dll_gpu8.dll";
            int cudnnVersion = 8;
            int cudartVersion = 112; // 10.2

            if (File.Exists(yoloDllFileName))
            {
                report.YoloGpuDll = true;
                var data = File.ReadAllBytes(yoloDllFileName);
                if (FindVersion(data, CudnnPattern, out int version))
                {
                    cudnnVersion = version;
                }

                if (FindVersion(data, CudartPattern, out version))
                {
                    cudartVersion = version;
                }
            }
```

Despite that, I get another error while loading models weights:

```
 Used GPU 0
 0 : compute_capability = 860, cudnn_half = 0, GPU: NVIDIA GeForce RTX 3080 Ti
net.optimized_memory = 0
mini_batch = 1730602928, batch = -455281152, time_steps = 1730602928, train = 0
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0

 cuDNN status Error in: file: C:\Users\User\Documents\Repositories\darknet\src\convolutional_layer.c : cudnn_convolutional_setup() : line: 253 : build time: Jan 25 2022 - 15:31:19

 cuDNN Error: CUDNN_STATUS_NOT_SUPPORTED
```

Could it be some cudnn version mismatch? What combination of Cuda and Cudnn do you have?

**Comment by AlgirdasKartavicius** [comment]
> Ok I found out that even when I put right `yolo_cpp_dll_gpu.dll` version to projects folder, when building, that dll is being changed to old one. But when I start the program and hit brake, then put right dll to the place, resume program, all dlls are found correctly. I can see that in `DefaultYoloSystemValidator.cs`. I changed `yolo_cpp_dll_gpu.dll` to `yolo_cpp_dll_gpu8.dll` not to be overwritten and it works.
> 
> ```cs
>     const string yoloDllFileName = "yolo_cpp_dll_gpu8.dll";
>             int cudnnVersion = 8;
>             int cudartVersion = 112; // 10.2
> 
>             if (File.Exists(yoloDllFileName))
>             {
>                 report.YoloGpuDll = true;
>                 var data = File.ReadAllBytes(yoloDllFileName);
>                 if (FindVersion(data, CudnnPattern, out int version))
>                 {
>                     cudnnVersion = version;
>                 }
> 
>                 if (FindVersion(data, CudartPattern, out version))
>                 {
>                     cudartVersion = version;
>                 }
>             }
> ```
> 
> Despite that, I get another error while loading models weights:
> 
> ```
>  Used GPU 0
>  0 : compute_capability = 860, cudnn_half = 0, GPU: NVIDIA GeForce RTX 3080 Ti
> net.optimized_memory = 0
> mini_batch = 1730602928, batch = -455281152, time_steps = 1730602928, train = 0
>    layer   filters  size/strd(dil)      input                output
>    0 Create CUDA-stream - 0
> 
>  cuDNN status Error in: file: C:\Users\User\Documents\Repositories\darknet\src\convolutional_layer.c : cudnn_convolutional_setup() : line: 253 : build time: Jan 25 2022 - 15:31:19
> 
>  cuDNN Error: CUDNN_STATUS_NOT_SUPPORTED
> ```
> 
> Could it be some cudnn version mismatch? What combination of Cuda and Cudnn do you have?

You need to change Initialize method inside YoloWrapper.cs file (https://github.com/zgabi/Yolo.Net/blob/master/src/Alturos.Yolo/YoloWrapper.cs).
 Batch size was added to darknet library.

```
 [DllImport(YoloLibraryName, EntryPoint = "init")]
 private static extern int InitializeYolo(string configurationFilename, string weightsFilename, int gpu, int batch_size);
```

**Comment by avresial** [comment]
> You need to change Initialize method inside YoloWrapper.cs file (https://github.com/zgabi/Yolo.Net/blob/master/src/Alturos.Yolo/YoloWrapper.cs). Batch size is added to darknet library.
> 
> ```
>  [DllImport(YoloLibraryName, EntryPoint = "init")]
>  private static extern int InitializeYolo(string configurationFilename, string weightsFilename, int gpu, int batch_size);
> ```

Ok
So I changed it. It works like a charm when it comes to loading yolo model. I'm given:
```
 try to allocate additional workspace_size = 378.61 MB
 CUDA allocate done!
```

But then one problem remains, when I try to detect any image exception occurs:
```
System.AccessViolationException: „Attempted to read or write protected memory. 
This is often an indication that other memory is corrupt.”
```

It is thrown in:
``` c#
public IEnumerable<YoloItem> Detect(string filepath)
  {
      if (!File.Exists(filepath))
      {
          throw new FileNotFoundException("Cannot find the file", filepath);
      }

      var container = new BboxContainer();
      var count = 0;
      switch (DetectionSystem)
      {
          case DetectionSystem.CPU:
              count = DetectImageCpu(filepath, ref container);
              break;
          case DetectionSystem.GPU:
              count = DetectImageGpu(filepath, ref container);
              break;
      }

      if (count == -1)
      {
          throw new NotImplementedException("C++ dll compiled incorrectly");
      }

      return Convert(container);
  }
```

on line:
``` c#
count = DetectImageGpu(filepath, ref container);
```

So i'm tring to fix that.

**Comment by zgabi** [comment]
When you find a solution, could you please share it? I'd appriciate a PR, too in my repo.
I don't have a compatible GPU, so I can't test it, but probably it would be useful for some users.

I'm adding the batch size parameter somehow...

**Comment by Paliscope** [comment]
Found this thread. Anyone got it to work on RTX30- ?

**Comment by avresial** [comment]
Yes, latest version does work on RTX30XX series. I have it running on 3080 TI

**Comment by Paliscope** [comment]
@avresial Would it be possible for you to post the reciepe...? 

"The for-dummies-version" with what yolo to use and versions of CUDA and CUDNN?

It would be very appreciated!

**Comment by avresial** [comment]
I'm using cuda 11.2 with cudnn 8.1

**Comment by Paliscope** [comment]
@avresial What yolodll are you using? Could you share that?

I was trying CUDA 11.6 and cudnn 8.4 with a DLL downloaded from here but dont get it to work

Will revert to the versions you are using, but can you share you _GPU dll?

Thanks

**Comment by avresial** [comment]
Sure, there are dlls: 
[Alturos Yolo dll](https://files.fm/f/d7cz7w642)
[GPU_DLL](https://files.fm/f/phkp2jvyd)

**Comment by AlgirdasKartavicius** [comment]
Follow this instruction:
![image](https://user-images.githubusercontent.com/26230733/163185885-4ce99b6b-eae5-4b03-963a-0a06a7bdf61f.png)

**Comment by Paliscope** [comment]
Thanks guys. Stilll dont get it to work...

1. Installed the latest drivers CHECK!
2. Installed CUDA 11.2 driver package CHECK
3. Downloaded cudnn-11.2-windows-x64-v8.1.0.77
4.
5. Cant find the DLL. I can see it in the step 3 but it is really tiny (compared to the cudnn64_7.dll)

Where can I get the OPENcv_World452.dll file...

Thank you!

Christian

**Comment by Paliscope** [comment]
Hi..

So got the opencv_world452.dll. My bad, 

I have all the DLLs in the output directory, including the yolo_cpp_dll_gpu.dll (the one provided by @avresial )

I have the latest drivers and a 3050 card.
I installed 11.2 CUDA toolkit
I Copied the cudnn64_8.dll to the output directory from cuDNN library (it is 260kb compared to 450MB for the cudnn64_7.dll)

I get the error: System.DllNotFoundException: 'Unable to load DLL 'yolo_cpp_dll_gpu': The specified module could not be found. (Exception from HRESULT: 0x8007007E)' when trying to instantiate the wrapper.

I guess it is dependency issue. Is it important to have the exect right version of Cuda (11.0)?


Any idea what I do wrong?


Best
Christian

**Comment by AlgirdasKartavicius** [comment]
Yes you need  Cuda 11.0

**Comment by avresial** [comment]
Hi, did you mannaged to run alturos on RTX40XX series card?

**Comment by zgabi** [comment]
I don't know how to run this package with a newer CUDA, but I'd recommend you to "upgrade" from this package to https://github.com/ivilson/Yolov7net
We are also using that package with RTX 3060 Laptop GPUs and with Quadro P600 GPU. I think it should also work with RTX40xx.
That package is using the microsoftonnx runtime, so needs a new model file format. So the upgrade is not trivial, but I suggest it.

**Comment by avresial** [comment]
> I don't know how to run this package with a newer CUDA, but I'd recommend you to "upgrade" from this package to https://github.com/ivilson/Yolov7net We are also using that package with RTX 3060 Laptop GPUs and with Quadro P600 GPU. I think it should also work with RTX40xx. That package is using the microsoftonnx runtime, so needs a new model file format. So the upgrade is not trivial, but I suggest it.

I see. Thx for a hint. I might upgrade to Yolov7 then.
